{{- if .Values.serviceAccount.create -}}
# The app's identity. Vault's role binds to THIS ServiceAccount name+namespace,
# so only pods running as this SA can read the secret.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cicd-demo.serviceAccountName" . }}
  labels:
    {{- include "cicd-demo.labels" . | nindent 4 }}
{{- end }}
